(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},k;if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var m;a:{var n={a:!0},p={};try{p.__proto__=n;m=p.a;break a}catch(a){}m=!1}k=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=k;var r=function(a,b){if(a&&Array.isArray(a)){var c=b?b.split("."):[""];return a.map(function(e){if(1==c.length)return e[c[0]];var d=e;c.forEach(function(f){d&&(d=d[f])});return d})}return[]},t=function(a,b){return a&&Array.isArray(a)?a.join(b||","):""},u={hex:function(a){return a?a.replace(/0x/,"#"):a},limit:function(a,b){return b?a&&Array.isArray(a)&&("string"==typeof b&&(b=parseInt(b,10)),!isNaN(b))?a.slice(0,b):a:a},lowercase:function(a){return a?a.toLowerCase():a}};u.join=t;
u.pixelvalue=function(a){if("undefined"!=typeof a)return a+"px"};u.pluck=r;u.pluckandjoin=function(a,b){return t(r(a,b))};u.uppercase=function(a){return a?a.toUpperCase():a};var v=function(a,b,c){if("undefined"!=typeof c){var e=document.querySelector("gwd-text-helper");e&&e.saveStyleOverride(a,b,c);a.style[b]=c}},w=function(a,b,c){c?a.classList.add(b):a.classList.remove(b)},x=function(a,b){if("undefined"!=typeof b){var c=document.querySelector("gwd-text-helper");c&&c.saveInitialText(a);a.textContent=b;c&&c.applyStylePreservation(a)}},y=function(a,b){a.style.display=!b||"string"==typeof b&&"false"==b.toLowerCase()?"none":""},z=function(a,b,c){"undefined"!=typeof c&&a.setAttribute(b,
c)};var A=/^bind-/,B=/^style-/,C=/^class-/,D=/^each-/,E=/-([a-z])/g;var F=function(a,b,c){c=void 0===c?null:c;var e=document.createEvent("CustomEvent");e.initCustomEvent(a,!0,!0,c);b.dispatchEvent(e)};var G=function(a){return String(a).replace(E,function(b,c){return c.toUpperCase()})},H=function(a){return!(!a||!A.test(a.name))},I=function(a){return!(!a||0!=a.name.indexOf("bind-each"))},J=function(){var a=HTMLElement.call(this)||this;a.o=null;a.l=!1;a.g=null;a.i=a.v.bind(a);return a},K=HTMLElement;J.prototype=g(K.prototype);J.prototype.constructor=J;
if(q)q(J,K);else for(var L in K)if("prototype"!=L)if(Object.defineProperties){var M=Object.getOwnPropertyDescriptor(K,L);M&&Object.defineProperty(J,L,M)}else J[L]=K[L];J.prototype.disconnectedCallback=function(){N(this)};
J.prototype.bindData=function(a,b){b=b||Array.prototype.slice.call(this.ownerDocument.querySelectorAll("*"));var c=(c=this.ownerDocument.querySelector("meta[name=environment]"))?c.getAttribute("content"):"";this.l="gwd-adwords"==c||"gwd-googleads"==c;this.o=a;N(this);(this.g=this.ownerDocument.querySelector("gwd-font-loader"))&&this.g.startDynamicFontLoading();b.forEach(this.h.bind(this,a));a=!0;this.g&&((a=this.g.endDynamicFontLoading())||this.g.addEventListener("gwdfontsloaded",this.i));return a};
J.prototype.h=function(a,b){if(!b.hasAttribute("gwd-bind-each-template")){for(var c,e=Array.prototype.slice.call(b.attributes),d=0;d<e.length;d++)if(I(e[d])){c=e[d];break}a=this.s.bind(this,b,a);c?a(c):e.filter(H).forEach(a)}};
J.prototype.s=function(a,b,c){var e=c.name,d=e.replace(A,"");if(B.test(d)){var f=d.replace(B,"");f=v.bind(null,a,G(f))}else C.test(d)?(f=d.replace(C,""),f=w.bind(null,a,f)):D.test(d)?(f=d.replace(D,""),f=this.m.bind(this,a,f,b)):f="text"===d?x.bind(null,a):"show"===d?y.bind(null,a):window.gwd&&window.gwd.binders&&"function"==typeof window.gwd.binders[d]?window.gwd.binders[d].bind(null,a):z.bind(null,a,d);e=a.getAttribute(e);b=(-1!==e.indexOf("|")?this.u.bind(this,b,e):this.j.bind(this,b,e)).call(a);
"style-font-family"==d&&this.g&&(b=this.g.parseFontList(b));"exit-override-url"==d&&(d=(d=c.value)&&d.match(/product\.\d+/i)?(d=d.match(/product\.(\d+)/i))&&d[1]?parseInt(d[1],10):null:null,null!=d&&a.setAttribute("product-index",d),this.l&&a.setAttribute("exit-id",c.value.replace(/\./g,"_")));f.apply(a,[b])};
J.prototype.m=function(a,b,c,e){var d=a.parentNode;if(d){for(var f=a.cloneNode(!0),l=Array.prototype.slice.call(f.attributes).filter(I),h=0;h<l.length;h++)f.removeAttribute(l[h].name);l=[];for(h=0;e&&h<e.length;h++)l.push(f.cloneNode(!0));F("gwdbindeachcloned",a,{instances:l});f=this.ownerDocument.createComment("gwd-bind-each-placeholder");d.insertBefore(f,a);d.removeChild(a);O(a);if(e&&0!=e.length){for(a=0;a<e.length;a++)c[b]=e[a],h=l[a],h.setAttribute("gwd-repeat-index",a),c.$index=a,Array.prototype.slice.call(h.querySelectorAll("*")).concat(h).forEach(this.h.bind(this,
c)),d.insertBefore(h,f);delete c[b]}}};var O=function(a){a.setAttribute("gwd-bind-each-template","");Array.prototype.slice.call(a.querySelectorAll("*")).forEach(function(b){b.setAttribute("gwd-bind-each-template","")})};J.prototype.j=function(a,b){if(a){if(b){b=b.replace("[",".");b=b.replace("]","");var c=a;b.split(".").forEach(function(e){c&&(c=c[e])});return c}return a}};
J.prototype.u=function(a,b){if(!b)return a;b=b.split("|");var c=b.shift().trim();a=this.j(a,c);if("undefined"!=typeof a){for(c=0;c<b.length;c++)a=P(this,a,b[c].trim());return a}};var P=function(a,b,c){c=c.split(" ").map(function(f){return f.trim()});var e=c.shift(),d=u[e];c.unshift(b);return d?d.apply(null,c):window.gwd&&window.gwd.formatters&&"function"==typeof window.gwd.formatters[e]?window.gwd.formatters[e].apply(a,c):b};J.prototype.v=function(){N(this);F("bindingfinished",this)};
var N=function(a){a.g&&(a.g.removeEventListener("gwdfontsloaded",a.i),a.g=null)};customElements.define("gwd-data-binder",J);}).call(this);
